function runTTE_raw(DataDir,fidx)

close all

% TTE Wrapper for Raw Data

if ~exist('DataDir','var')
    DataDir = pwd;
end
if ~exist('fidx','var')
    fidx = -1;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Inputs to procTTE
options.dataflow = struct(...
    'display', 1 ...
    ,'ecg_test', 0 ...
    ,'ARFI', 1 ...
    ,'SWEI', 0 ...
    ,'oneSided', 1 ...
    ,'setID',fidx ...
    ,'saveRes', 0 ...
    );
options.dispEst = struct(...
    'method','Loupas'...
    ,'ref_type','Progressive' ...   % anchored/progressive
    ,'ref_idx',[] ...
    ,'nreverb', 2 ...         % Not having the correct nreverb could mess up displacements when using progressive ref_type
    ,'interpFactor', 5 ...
    ,'kernelLength', 4 ...
    ,'DOF_fraction', 1 ... % Fraction of Depth of Field (around focus) to compute displacements for. DOF = 9*lambda*F_num^2
    ,'searchRegion', 4 ...
    ,'ccmode', 1 ...
    );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Inputs to dispTTE
options.motionFilter = struct(...
    'enable', 1 ...
    ,'method','Both' ... % Polynomial/LPF/Both
    ... % Parameters for Polynomial filter
    ,'order', 1 ...
    ,'timeRange_push',[-1.5 -1 4.5 5] ...
    ,'pre_offset', -6.5 ...
    ... % Parameters for Bandpass filter
    ,'LPF_Cutoff', 750 ...
    );
options.motionFilter.timeRange_pre = options.motionFilter.timeRange_push + options.motionFilter.pre_offset;

options.display = struct(...
    'theme', 'dark' ... % light/dark
    ,'IQrange',[-40 0] ...
    ,'gateWidth', 5 ...
    ,'gateOffset', 0 ...
    ,'n_pts', 5 ...
    ,'medfilt',[1 0.15] ... % median filter parameters - [axial (mm) acqTime (s)]
    ,'cc_filt', 1 ...
    ,'cc_thresh', 0.995 ...
    ... % ARFI Display Parameters
    ,'disprange',[-5 15] ...
    ,'normalize', 0 ...
    ,'t_disp_push', 0.5 ...
    ,'extras', 0 ...
    ... % SWEI Display Parameters
    ,'velrange',[ ] ...
    ,'axial_scan',0 ...
    ,'sw_movie',0 ...
    ,'dvt_plots',0 ...
    ,'sw_display','disp' ... % Display displacements ('disp') or velocity ('vel') data
    );
options.display.t_disp_pre = options.motionFilter.timeRange_pre(1) + (options.display.t_disp_push - options.motionFilter.timeRange_push(1));

options.calcSWS = struct(...
    'enable',0 ...
    ,'method','LinReg' ... LinReg/ LatSum
    ,'metric', 'TTP' ...
    ,'r2_threshold',0.5 ...
    ,'SWSrange',[0 7] ...
    );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Function Call
procTTE(DataDir,fidx,options)

clear
clc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%